### ISSUE TITLE
Add travis build

### ISSUE THREAD

**Issue by thijstriemstra** [jackedgson/crunker#10]
Would be nice to build and test this library on travis-ci.org

**Comment by jaggad** [comment]
Agreed, I attempted this before, however the testing aspect created many issues due to the fact that I was working with Web Audio API and could not find any mocks and headless chrome (Pupeteer) wasn't out at that time. 

If you want to take this on at all, I'd be happy to accept a PR. But as of now it's not a priority for me.

**Comment by thijstriemstra** [comment]
@jackedgson how do I run the unit tests?

**Comment by jaggad** [comment]
Currently only method is to run in browser.

Navigate to the `test/test.html` file and open it in your browser. The tests will be run on reload.

**Comment by fzxt** [comment]
would http://mohayonao.github.io/web-audio-test-api/ be viable?

**Comment by thijstriemstra** [comment]
using a headless chrome on travis should work fine.

**Comment by jaggad** [comment]
Agreed, headless chrome would be the best solution.
