### ISSUE TITLE
Sample rate change

### ISSUE THREAD

**Issue by trakzco** [jackedgson/crunker#15]
We use Crunker to merge full length tracks with audio tags. Users who upload their tracks to be tagged on Windows machine report that that the audio has been pitched down (i.e the original track has been stretched to meet a large sample rate). However, this issue cannot be replicated when using crunker to merge the same audio on Windows machines.

**Comment by jaggad** [comment]
Have you tried customising the output sample rate with the `sampleRate` config option?
It may be that we need to instead detect the sampleRate of the files and use their sample rate as the output value as well, though I'm not certain of the best way to go about this.

**Comment by chasecreates** [comment]
Yes, we did something along the lines of detecting sampleRate of files and using them as the param, but still pitching some down.

**Comment by polarathene** [comment]
Not sure if this is related or helps. In my case I have input of 24kHz audio files and `decodeAudioData()` uses the `AudioContext()` sample rate which is defined by the output audio device/OS rather than input files(which could explain your conflicting reproduction on Windows). Any change to the returned `AudioBuffer` sampling rate will then affect the duration(stretch/squeeze) of the audio.

`AudioContext()` at creation can take an options object that supports `latency` and `sampleRate` fields, however this was an addition to the spec and requires browser support. Firefox supports it well but Chrome only supports `latency` option. So any usage with Electron apps are unable to alter the default sample rate for the audio context.

[Here is the chrome tracking issue](https://bugs.chromium.org/p/chromium/issues/detail?id=432248) for progress on supporting `sampleRate` option. It's an old issue but looks like it'll eventually arrive this year.

Other browsers are [lacking support entirely](https://developer.mozilla.org/en-US/docs/Web/API/AudioContextOptions#Browser_compatibility).

If you're ok with the sampling rate being changed to the `AudioContext` default sample rate(varies as stated above), then instead of the hardcoded(or user provided) `44100` default value for `createBuffer` to use as sample rate, you could reference the contexts one and use that? For audio inputs that are lower sample rates, they should not be affected in quality, for higher sample rates I guess you'll lose samples but the duration should be unaffected. Otherwise, if differing from the default sample rate AudioContext uses, you'll probably have to support resampling?

Raymond Toy is part of the Web Audio W3C group and a Googler working on the Web Audio API([at least was in 2016](https://stackoverflow.com/questions/34201957/why-are-decodeaudiodata-results-different-on-different-os#comment56293302_34201957)) , he provides [an alternative way to resample the audio by using `OfflineAudioContext()`](https://stackoverflow.com/a/36636441) if that's an option.

**Comment by polarathene** [comment]
Hello, I took the code snippet from Raymond Toy on StackOverflow that I linked to. I have tested it and found it works for the most part, but was causing the output to be a different duration(no stretch/squuezing of data, just larger unused buffer, though if upsampling may result in trimmed audio).

Here is my code with comments to make it more clear:

```JS
const resample = async (input_buffer, target_rate) => {
  const len = input_buffer.length
  const src_rate = input_buffer.sampleRate
  // New sampleRate requires adjusted buffer length to retain duration
  const target_len = len * (target_rate / src_rate)

  // Until better support for `AudioContext({sampleRate}),
  // use `OfflineAudioContext` which supports setting the sampleRate
  const c = new OfflineAudioContext(
    1,
    target_len,
    target_rate
  );

  // Copy the`AudioContext` buffer so `OfflineAudioContext` can use it
  const b = c.createBuffer(
    1,
    len,
    src_rate
  );
  b.copyToChannel(input_buffer.getChannelData(0), 0);

  // Setup the audio graph to render (input buffer resampled into output buffer)
  const s = c.createBufferSource();
  s.buffer = b;
  s.connect(c.destination);
  s.start();

  return await c.startRendering()
}
```

You can use it like this:

```JS
    const resampled = await resample(buffer, 24000)
```

Hope it helps :) Do note this is probably only useful for downsampling from whatever `AudioContext` has resampled your audio to, which in my case original was 24kHz, so the higher sample rate was just causing extra file size. If you have the same or higher sample rate as `AudioContext` defaults to, might as well just use it's sample rate?

I think you can use `OfflineAudioContext` to avoid the (lossy?) resample and set your own sample rate, but it appears that you'd need to know not only the sample rate but also number of channels and how big the buffer size should be in advance before you create it and later use `.decodeAudioData()`.
