### ISSUE TITLE
Adding To Project

### ISSUE THREAD

**Issue by hussam123-lab** [jackedgson/crunker#27]
How do I use this in my html project as in generally you'd do <script src = "  "> </script>. However I cant seem to find the link what is the alternative way of doing this? Also its raising an error with export in the js file: Uncaught SyntaxError: Unexpected token 'export'.  Sorry for the stupid questions I'm new to all this.

**Comment by Alynva** [comment]
The error is because this library is a ES6 module, and the browser doesn't recognize it by default. Try do something like this:
```html
<script type="module">
    import crunker from "./crunker.js"
    
    console.log(crunker)

    let audio = new Crunker();
    // ...
</script>
```

You can also get the source from a CDN's url, like this:

```js
import crunker from "https://cdn.jsdelivr.net/gh/jackedgson/crunker/src/crunker.js"
```

Read more [here](https://www.sitepoint.com/using-es-modules/) or even better [here in the MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)

**Comment by jaggad** [comment]
@hussam123-lab Yes, the library is an ES6 Module. It will have to be imported.
