### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Moebytes** [jackedgson/crunker#51]
.

**Comment by jaggad** [comment]
@Tenpi Do you have an idea why Firefox fails this behaviour?

The crunker download code is very simple. It just creates and anchor link, adds a blob as the href and "clicks" it. I am open to supporting different behaviour though. 

Can you maybe try and see if you can add the returned anchor link element to the DOM and then manually click it and see if that works? Could be a spam prevention thing where user interaction is required.

```js
download(blob, filename) {    
  const name = filename || "crunker";   
  const a = document.createElement("a");    
  a.style = "display: none";    
  a.href = this._renderURL(blob);    
  a.download = `${name}.${blob.type.split("/")[1]}`;   
  a.click();    
  return a;  
}
```

**Comment by Tenpi** [comment]
> @Tenpi Do you have an idea why Firefox fails this behaviour?
> 
> The crunker download code is very simple. It just creates and anchor link, adds a blob as the href and "clicks" it. I am open to supporting different behaviour though.

I found the reason on this answer:
https://stackoverflow.com/questions/30444250/download-attribute-not-working-in-firefox-but-working-in-chrome

In Firefox, you can only download files from the same domain which is why it was only working in Chrome. I did find a solution though, since this is a browser extension I had the browser handle the download instead. So instead of using crunker.download, I just obtained the url:

```js
const downloadM3U = async (url, title) => {
  const m3u = await fetch(url).then((r) => r.text())
  const urls = m3u.match(/(http).*?(?=\s)/gm)
  let crunker = new Crunker.default({sampleRate: 48000})
  const buffers = await crunker.fetchAudio(...urls)
  const merged = await crunker.concatAudio(buffers)
  const output = await crunker.export(merged, "audio/mp3")
  return output.url
}
```
And handled the downloads myself:

```js
chrome.downloads.download({url, filename, conflictAction: "overwrite"})
```

**Comment by Alynva** [comment]
That's an extension?
