### ISSUE TITLE
Expose AudioContext

### ISSUE THREAD

**Issue by lmiller1990** [jackedgson/crunker#66]
Hi,

I'm using Crunker in a small rhythm game prototype; I need the current playback time which you can normally get from `AudioContext.prototype.getOutputTimestamp`, but I'm unable to do this since Crunker isn't exposing the audioContext.

Is it possible to expose this, or against the design philosophy?

**Comment by jaggad** [comment]
I believe previously it was actually accessible by calling `crunker._context`. After the typescript refactor this may no longer be possible which could be considered a breaking change.

I see no reason not to expose the context and many reasons (such as your's) to expose it to be interfaces with. 

I believe this will only make the library more powerful.

If you'd like to create a PR and to add a getter, for example, which returns the context then please go for it and I'll create an npm release shortly after. Otherwise, if you're unsure how to do this then I'm happy to help.

Do you want to have a go at extending the functionality first. Please also update the docs with the methods as well.

Hope this helps.

**Comment by davwheat** [comment]
I agree in this situation, too.

The Typescript refactor hasn't changed this, but has made it more clear that access to this is considered private API. In JavaScript there isn't any way to restrict access to class attributes, hence the private access modifier is more documentation than anything else.

**Comment by jaggad** [comment]
Does typescript intellisense autocomplete or suggest for private properties though, that may be part of the confusion here. I actually don't know if it does or not, would be easy to test I suppose.

**Comment by davwheat** [comment]
No, you're right, it would not.

**Comment by Alynva** [comment]
> I agree in this situation, too.
> 
> The Typescript refactor hasn't changed this, but has made it more clear that access to this is considered private API. In JavaScript there isn't any way to restrict access to class attributes, hence the private access modifier is more documentation than anything else.

Using `#` instead of `_` work for private attributes/methods: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by davwheat** [comment]
Yes, but that's only supported in very recent browsers, most notably iOS 14.5+, which could significantly limit Crunker's usefulness.

**Comment by Alynva** [comment]
I think that private/public things is just for the developer experience, the final user will not ever notice this difference. And the developer can edit the source code on his machine and use whatever he want. So its not like hiding private keys or something...

The library is already in TS, I'm not suggesting going back to JS just for this...

**Comment by jaggad** [comment]
@lmiller1990 would you like to create a PR for this and become a contributor, or one of us can implement the PR for you. Will be a very minor change really.

**Comment by lmiller1990** [comment]
Whoever gets there first, it's like a 2 liner. I might have time this weekend - seems like there's a lot of momentum behind this feature; as long as we are all in agreement, anyone can write the code/make the associated PR :)

**Comment by lmiller1990** [comment]
Ok, PR https://github.com/jackedgson/crunker/pull/67
