### ISSUE TITLE
Concatenated Files Too Large

### ISSUE THREAD

**Issue by aintHuman** [jackedgson/crunker#81]
Not sure what is causing this, hoping someone can help me out.

When I concatenate 3 mp3 files that are each about 8.5Mb in size, fetched from AWS S3 bucket, the resultant mp3 file after concatenation and download is a whopping 280Mb, which is about 10x what I would expect.

If I get that large file and then using a program like VLC player I stream to export as a fresh mp3 file, it is reduced to about 30Mb, closer to what I would expect. 

FWIW, The Content-Type metadata of the files on the S3 bucket is set to audio/mpeg.

Is there some obvious configuration/setting that can resolve this ?

**Comment by MikeyZat** [comment]
I assume you use the `export` method at the end of your Crunker workflow? The problem is that it exports the file in `.wav` format (even if you specify `.mp3`) as described [here](https://github.com/jaggad/crunker#crunkerexportbuffer-type). This is probably causing the increase in size.

The solution would be using a 3rd party to convert `AudioBuffer` directly to `mp3`, or optionally the exported `.wav` to `.mp3`. Unless you'd like to add export to mp3 method to `Crunker` - that would be lovely ;)

**Comment by aintHuman** [comment]
yeah, that would be the reason. thanks

**Comment by jaggad** [comment]
Export to mp3 is a welcome addition. Not something I plan on tackling but I think it would be a useful and desirable addition.
